[package]
name = "ic-radix-signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.10.8"
ic-cdk = "0.13.3"
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto" }
